set(SOURCES
	include/F4SE/API.h
	include/F4SE/F4SE.h
	include/F4SE/Impl/PCH.h
	include/F4SE/InputMap.h
	include/F4SE/Interfaces.h
	include/F4SE/Logger.h
	include/F4SE/Trampoline.h
	include/F4SE/Version.h
	include/RE/A/ACTION_OBJECT.h
	include/RE/A/ACTOR_BASE_DATA.h
	include/RE/A/ACTOR_CRITICAL_STAGE.h
	include/RE/A/ACTOR_LIFE_STATE.h
	include/RE/A/ACTOR_LOS_LOCATION.h
	include/RE/A/ACTOR_VALUE_MODIFIER.h
	include/RE/A/ACTOR_VISIBILITY_MASK.h
	include/RE/A/ADDON_DATA.h
	include/RE/A/AIDATA_GAME.h
	include/RE/A/AIProcess.h
	include/RE/A/AITimeStamp.h
	include/RE/A/AITimer.h
	include/RE/A/AMMO_DATA.h
	include/RE/A/ActionInput.h
	include/RE/A/ActiveEffect.h
	include/RE/A/ActiveEffectList.h
	include/RE/A/ActiveEffectReferenceEffectController.h
	include/RE/A/Actor.h
	include/RE/A/ActorEquipManager.h
	include/RE/A/ActorEquipManagerEvent.h
	include/RE/A/ActorItemEquipped.h
	include/RE/A/ActorKill.h
	include/RE/A/ActorPackage.h
	include/RE/A/ActorPackageData.h
	include/RE/A/ActorState.h
	include/RE/A/ActorUtils.h
	include/RE/A/ActorValue.h
	include/RE/A/ActorValueEvents.h
	include/RE/A/ActorValueInfo.h
	include/RE/A/ActorValueOwner.h
	include/RE/A/ActorValueStorage.h
	include/RE/A/AimModel.h
	include/RE/A/AlarmPackage.h
	include/RE/A/AlchemyItem.h
	include/RE/A/AnimationStanceNodeLocationData.h
	include/RE/A/AnimationSystemUtils.h
	include/RE/A/ApplyChangesFunctor.h
	include/RE/A/ApplyColorUpdateEvent.h
	include/RE/A/ArrowProjectile.h
	include/RE/A/AttachTechniqueInput.h
	include/RE/A/AttackBlockHandler.h
	include/RE/A/AttackData.h
	include/RE/A/AutoMoveHandler.h
	include/RE/B/BGSAcousticSpace.h
	include/RE/B/BGSAction.h
	include/RE/B/BGSActorCellEvent.h
	include/RE/B/BGSActorDeathEvent.h
	include/RE/B/BGSActorEvent.h
	include/RE/B/BGSAddonNode.h
	include/RE/B/BGSAimModel.h
	include/RE/B/BGSAnimationSystemUtils.h
	include/RE/B/BGSArtObject.h
	include/RE/B/BGSAssociationType.h
	include/RE/B/BGSAttachParentArray.h
	include/RE/B/BGSAttackData.h
	include/RE/B/BGSAttackDataForm.h
	include/RE/B/BGSAttackDataMap.h
	include/RE/B/BGSAttractionRule.h
	include/RE/B/BGSAudioEffectChain.h
	include/RE/B/BGSBaseAlias.h
	include/RE/B/BGSBehaviorGraphModel.h
	include/RE/B/BGSBehaviorRootData.h
	include/RE/B/BGSBendableSpline.h
	include/RE/B/BGSBipedObjectForm.h
	include/RE/B/BGSBlockBashData.h
	include/RE/B/BGSBodyPart.h
	include/RE/B/BGSBodyPartData.h
	include/RE/B/BGSBodyPartDefs.h
	include/RE/B/BGSCameraPath.h
	include/RE/B/BGSCameraShot.h
	include/RE/B/BGSCharacterMorph.h
	include/RE/B/BGSCharacterTint.h
	include/RE/B/BGSCollisionLayer.h
	include/RE/B/BGSColorForm.h
	include/RE/B/BGSComponent.h
	include/RE/B/BGSConstructibleObject.h
	include/RE/B/BGSCraftItemEvent.h
	include/RE/B/BGSCraftingUseSound.h
	include/RE/B/BGSCreatedObjectManager.h
	include/RE/B/BGSDamageType.h
	include/RE/B/BGSDebris.h
	include/RE/B/BGSDefaultObject.h
	include/RE/B/BGSDefaultObjectManager.h
	include/RE/B/BGSDestructibleObjectForm.h
	include/RE/B/BGSDialogueBranch.h
	include/RE/B/BGSDirectionalAmbientLightingColors.h
	include/RE/B/BGSDualCastData.h
	include/RE/B/BGSDualCastDataDEF.h
	include/RE/B/BGSDynamicPersistenceManager.h
	include/RE/B/BGSEncounterZone.h
	include/RE/B/BGSEntryPoint.h
	include/RE/B/BGSEquipIndex.h
	include/RE/B/BGSEquipSlot.h
	include/RE/B/BGSEquipType.h
	include/RE/B/BGSExplosion.h
	include/RE/B/BGSExplosionData.h
	include/RE/B/BGSFeaturedItemMessage.h
	include/RE/B/BGSFootstep.h
	include/RE/B/BGSFootstepSet.h
	include/RE/B/BGSForcedLocRefType.h
	include/RE/B/BGSGodRays.h
	include/RE/B/BGSHackTerminal.h
	include/RE/B/BGSHazard.h
	include/RE/B/BGSHazardData.h
	include/RE/B/BGSHeadPart.h
	include/RE/B/BGSIdleCollection.h
	include/RE/B/BGSIdleMarker.h
	include/RE/B/BGSImpactData.h
	include/RE/B/BGSImpactDataSet.h
	include/RE/B/BGSInstanceNamingRules.h
	include/RE/B/BGSInstanceNamingRulesForm.h
	include/RE/B/BGSInstancedQuestObjective.h
	include/RE/B/BGSInventoryInterface.h
	include/RE/B/BGSInventoryItem.h
	include/RE/B/BGSInventoryItemEvent.h
	include/RE/B/BGSInventoryList.h
	include/RE/B/BGSInventoryListEvent.h
	include/RE/B/BGSKeyword.h
	include/RE/B/BGSKeywordForm.h
	include/RE/B/BGSLargeRefData.h
	include/RE/B/BGSLensFlare.h
	include/RE/B/BGSLightingTemplate.h
	include/RE/B/BGSListForm.h
	include/RE/B/BGSLocalizedString.h
	include/RE/B/BGSLocation.h
	include/RE/B/BGSLocationRefType.h
	include/RE/B/BGSMaterialObject.h
	include/RE/B/BGSMaterialSwap.h
	include/RE/B/BGSMaterialType.h
	include/RE/B/BGSMenuDisplayObject.h
	include/RE/B/BGSMenuIcon.h
	include/RE/B/BGSMessage.h
	include/RE/B/BGSMessageIcon.h
	include/RE/B/BGSMod.h
	include/RE/B/BGSModelMaterialSwap.h
	include/RE/B/BGSMovableStatic.h
	include/RE/B/BGSMovementType.h
	include/RE/B/BGSMusicTrackFormWrapper.h
	include/RE/B/BGSMusicType.h
	include/RE/B/BGSNativeTerminalForm.h
	include/RE/B/BGSNavmeshableObject.h
	include/RE/B/BGSNote.h
	include/RE/B/BGSNumericIDIndex.h
	include/RE/B/BGSObjectInstance.h
	include/RE/B/BGSObjectInstanceExtra.h
	include/RE/B/BGSOpenCloseForm.h
	include/RE/B/BGSOutfit.h
	include/RE/B/BGSOverridePackCollection.h
	include/RE/B/BGSPackIn.h
	include/RE/B/BGSPerk.h
	include/RE/B/BGSPerkRankArray.h
	include/RE/B/BGSPickLockEvent.h
	include/RE/B/BGSPickupPutdownSounds.h
	include/RE/B/BGSPreloadable.h
	include/RE/B/BGSPreviewTransform.h
	include/RE/B/BGSPrimitive.h
	include/RE/B/BGSProjectile.h
	include/RE/B/BGSProjectileData.h
	include/RE/B/BGSPropertySheet.h
	include/RE/B/BGSQuestInstanceText.h
	include/RE/B/BGSRefAlias.h
	include/RE/B/BGSRefAliasInstanceData.h
	include/RE/B/BGSReferenceEffect.h
	include/RE/B/BGSRelationship.h
	include/RE/B/BGSReverbParameters.h
	include/RE/B/BGSSaveLoadManager.h
	include/RE/B/BGSSaveLoadThread.h
	include/RE/B/BGSScene.h
	include/RE/B/BGSSceneAction.h
	include/RE/B/BGSSceneActionConversationBase.h
	include/RE/B/BGSSceneActionDialogue.h
	include/RE/B/BGSSceneActionNPCResponseDialogue.h
	include/RE/B/BGSSceneActionPackage.h
	include/RE/B/BGSSceneActionPlayerDialogue.h
	include/RE/B/BGSSceneActionRadio.h
	include/RE/B/BGSSceneActionStartScene.h
	include/RE/B/BGSSceneActionTimer.h
	include/RE/B/BGSScenePhase.h
	include/RE/B/BGSShaderParticleGeometryData.h
	include/RE/B/BGSSkinForm.h
	include/RE/B/BGSSoundCategory.h
	include/RE/B/BGSSoundCategorySnapshot.h
	include/RE/B/BGSSoundDescriptorForm.h
	include/RE/B/BGSSoundKeywordMapping.h
	include/RE/B/BGSSoundOutput.h
	include/RE/B/BGSSoundTagComponent.h
	include/RE/B/BGSSoundTagSet.h
	include/RE/B/BGSStaticCollection.h
	include/RE/B/BGSStoryEventManager.h
	include/RE/B/BGSStoryManagerBranchNode.h
	include/RE/B/BGSStoryManagerEventNode.h
	include/RE/B/BGSStoryManagerNodeBase.h
	include/RE/B/BGSStoryManagerQuestNode.h
	include/RE/B/BGSStoryManagerTreeForm.h
	include/RE/B/BGSStoryManagerTreeVisitor.h
	include/RE/B/BGSSynchronizedAnimationManager.h
	include/RE/B/BGSTalkingActivator.h
	include/RE/B/BGSTerminal.h
	include/RE/B/BGSTextureModel.h
	include/RE/B/BGSTextureSet.h
	include/RE/B/BGSTopicSubtypeUnion.h
	include/RE/B/BGSTransform.h
	include/RE/B/BGSTypedFormValuePair.h
	include/RE/B/BGSTypedKeywordValue.h
	include/RE/B/BGSVoiceType.h
	include/RE/B/BGSZoomData.h
	include/RE/B/BIPED_MODEL.h
	include/RE/B/BIPED_OBJECT.h
	include/RE/B/BIPOBJECT.h
	include/RE/B/BSAnimationGraphEvent.h
	include/RE/B/BSAnimationGraphManager.h
	include/RE/B/BSAnimationGraphVariableCache.h
	include/RE/B/BSAudioCallbacks.h
	include/RE/B/BSAudioInit.h
	include/RE/B/BSAudioManager.h
	include/RE/B/BSAudioUtil.h
	include/RE/B/BSAwardsSystemUtility.h
	include/RE/B/BSBTreeFile.h
	include/RE/B/BSBatchRenderer.h
	include/RE/B/BSBound.h
	include/RE/B/BSCRC32.h
	include/RE/B/BSContainer.h
	include/RE/B/BSCoreTypes.h
	include/RE/B/BSCriticalSection.h
	include/RE/B/BSEventFlag.h
	include/RE/B/BSExtraData.h
	include/RE/B/BSFadeNode.h
	include/RE/B/BSFile.h
	include/RE/B/BSFixedString.h
	include/RE/B/BSFlattenedBoneTree.h
	include/RE/B/BSFurnitureMarker.h
	include/RE/B/BSGFxDisplayObject.h
	include/RE/B/BSGFxFunctionBase.h
	include/RE/B/BSGFxFunctionHandler.h
	include/RE/B/BSGFxObject.h
	include/RE/B/BSGFxShaderFXTarget.h
	include/RE/B/BSGeometry.h
	include/RE/B/BSGraphics.h
	include/RE/B/BSHandleRefObject.h
	include/RE/B/BSIAudioEffectChain.h
	include/RE/B/BSIMusicTrack.h
	include/RE/B/BSIMusicType.h
	include/RE/B/BSIReverbType.h
	include/RE/B/BSISoundCategory.h
	include/RE/B/BSISoundDescriptor.h
	include/RE/B/BSISoundOutputModel.h
	include/RE/B/BSInputDevice.h
	include/RE/B/BSInputDeviceManager.h
	include/RE/B/BSInputEnableLayer.h
	include/RE/B/BSInputEnableManager.h
	include/RE/B/BSInputEventReceiver.h
	include/RE/B/BSInputEventSingleUser.h
	include/RE/B/BSInputEventUser.h
	include/RE/B/BSIntrusiveRefCounted.h
	include/RE/B/BSLensFlareRenderData.h
	include/RE/B/BSLightingShaderMaterial.h
	include/RE/B/BSLightingShaderMaterialBase.h
	include/RE/B/BSLightingShaderProperty.h
	include/RE/B/BSMTAManager.h
	include/RE/B/BSMagicShaderParticles.h
	include/RE/B/BSMaterialObject.h
	include/RE/B/BSMemStorage.h
	include/RE/B/BSModelDB.h
	include/RE/B/BSNavmesh.h
	include/RE/B/BSNavmeshClosedDoorInfo.h
	include/RE/B/BSNavmeshCoverEdge.h
	include/RE/B/BSNavmeshCoverEdgeBase.h
	include/RE/B/BSNavmeshEdgeExtraInfo.h
	include/RE/B/BSNavmeshGrid.h
	include/RE/B/BSNavmeshInfoMap.h
	include/RE/B/BSNavmeshTriangle.h
	include/RE/B/BSNavmeshTriangleDoorPortal.h
	include/RE/B/BSNavmeshTriangleEdgePortal.h
	include/RE/B/BSNavmeshVertex.h
	include/RE/B/BSNavmeshWaypoint.h
	include/RE/B/BSPackedTaskQueue.h
	include/RE/B/BSPointerAllocator.h
	include/RE/B/BSPointerHandle.h
	include/RE/B/BSPreCulledObjects.h
	include/RE/B/BSPrecomputedNavmeshInfoPathMap.h
	include/RE/B/BSRandom.h
	include/RE/B/BSReloadShaderI.h
	include/RE/B/BSResource.h
	include/RE/B/BSResourceNiBinaryStream.h
	include/RE/B/BSResource_Archive2_AsyncReaderStream.h
	include/RE/B/BSResource_Archive2_ClearRegistryEvent.h
	include/RE/B/BSResource_Archive2_DataReader.h
	include/RE/B/BSResource_Archive2_Index.h
	include/RE/B/BSResource_Archive2_ReaderStream.h
	include/RE/B/BSResource_Archive2_RegisteredEvent.h
	include/RE/B/BSResource_Archive2_StreamOpenedEvent.h
	include/RE/B/BSResource_AsyncStream.h
	include/RE/B/BSResource_EntryBase.h
	include/RE/B/BSResource_EntryBucketQueue.h
	include/RE/B/BSResource_EntryDBBaseUtil.h
	include/RE/B/BSResource_EntryQueue.h
	include/RE/B/BSResource_ErrorCode.h
	include/RE/B/BSResource_FileID.h
	include/RE/B/BSResource_GlobalLocations.h
	include/RE/B/BSResource_GlobalPaths.h
	include/RE/B/BSResource_ICacheDriveOp.h
	include/RE/B/BSResource_ID.h
	include/RE/B/BSResource_IEntryDB.h
	include/RE/B/BSResource_Info.h
	include/RE/B/BSResource_Location.h
	include/RE/B/BSResource_LooseFileStreamBase.h
	include/RE/B/BSResource_SDirectory2.h
	include/RE/B/BSResource_SeekMode.h
	include/RE/B/BSResource_Stream.h
	include/RE/B/BSResource_StreamBase.h
	include/RE/B/BSSaveDataSystemUtility.h
	include/RE/B/BSSaveDataSystemUtilityImage.h
	include/RE/B/BSScaleformExternalTexture.h
	include/RE/B/BSScaleformManager.h
	include/RE/B/BSScaleformRenderer.h
	include/RE/B/BSScaleformTranslator.h
	include/RE/B/BSScriptUtil.h
	include/RE/B/BSScript_Array.h
	include/RE/B/BSScript_ArrayWrapper.h
	include/RE/B/BSScript_CompiledScriptLoader.h
	include/RE/B/BSScript_ErrorLogger.h
	include/RE/B/BSScript_ICachedErrorMessage.h
	include/RE/B/BSScript_IClientVM.h
	include/RE/B/BSScript_IComplexType.h
	include/RE/B/BSScript_IHandleReaderWriter.h
	include/RE/B/BSScript_ILoader.h
	include/RE/B/BSScript_IMemoryPagePolicy.h
	include/RE/B/BSScript_IObjectHandlePolicy.h
	include/RE/B/BSScript_IObjectProcessor.h
	include/RE/B/BSScript_ISavePatcherInterface.h
	include/RE/B/BSScript_IStackCallbackFunctor.h
	include/RE/B/BSScript_IStackCallbackSaveInterface.h
	include/RE/B/BSScript_IVMDebugInterface.h
	include/RE/B/BSScript_IVMObjectBindInterface.h
	include/RE/B/BSScript_IVirtualMachine.h
	include/RE/B/BSScript_Internal_AttachedScript.h
	include/RE/B/BSScript_Internal_CodeTasklet.h
	include/RE/B/BSScript_Internal_EventRelay.h
	include/RE/B/BSScript_Internal_FunctionMessage.h
	include/RE/B/BSScript_Internal_IFuncCallQuery.h
	include/RE/B/BSScript_Internal_IFunction.h
	include/RE/B/BSScript_Internal_IProfilePolicy.h
	include/RE/B/BSScript_Internal_IVMSaveLoadInterface.h
	include/RE/B/BSScript_Internal_LinkerProcessor.h
	include/RE/B/BSScript_Internal_NativeFunctionBase.h
	include/RE/B/BSScript_Internal_RawFuncCallQuery.h
	include/RE/B/BSScript_Internal_ReadableStringTable.h
	include/RE/B/BSScript_Internal_ReadableTypeTable.h
	include/RE/B/BSScript_Internal_ScriptFunction.h
	include/RE/B/BSScript_Internal_Stack.h
	include/RE/B/BSScript_Internal_SuspendedStack.h
	include/RE/B/BSScript_Internal_VDescTable.h
	include/RE/B/BSScript_Internal_VirtualMachine.h
	include/RE/B/BSScript_Internal_WritableStringTable.h
	include/RE/B/BSScript_Internal_WritableTypeTable.h
	include/RE/B/BSScript_LogEvent.h
	include/RE/B/BSScript_MergedBoundScript.h
	include/RE/B/BSScript_Object.h
	include/RE/B/BSScript_ObjectBindPolicy.h
	include/RE/B/BSScript_ObjectTypeInfo.h
	include/RE/B/BSScript_PackedInstructionStream.h
	include/RE/B/BSScript_PropertyGroupInfo.h
	include/RE/B/BSScript_PropertyTypeInfo.h
	include/RE/B/BSScript_SimpleAllocMemoryPagePolicy.h
	include/RE/B/BSScript_StackFrame.h
	include/RE/B/BSScript_StatsEvent.h
	include/RE/B/BSScript_Struct.h
	include/RE/B/BSScript_StructTypeInfo.h
	include/RE/B/BSScript_TypeInfo.h
	include/RE/B/BSScript_Variable.h
	include/RE/B/BSSemaphore.h
	include/RE/B/BSShader.h
	include/RE/B/BSShaderData.h
	include/RE/B/BSShaderMaterial.h
	include/RE/B/BSShaderProperty.h
	include/RE/B/BSShaderPropertyLightData.h
	include/RE/B/BSShaderTechniqueIDMap.h
	include/RE/B/BSShaderTextureSet.h
	include/RE/B/BSSimpleList.h
	include/RE/B/BSSoundHandle.h
	include/RE/B/BSSpinLock.h
	include/RE/B/BSSpring_SpringState.h
	include/RE/B/BSSteamAwardsSystemUtility.h
	include/RE/B/BSStorage.h
	include/RE/B/BSStorageDefs.h
	include/RE/B/BSStreamHeader.h
	include/RE/B/BSStringPool.h
	include/RE/B/BSStringT.h
	include/RE/B/BSSystemFile.h
	include/RE/B/BSSystemFileStreamer.h
	include/RE/B/BSTArray.h
	include/RE/B/BSTAtomicValue.h
	include/RE/B/BSTBTree.h
	include/RE/B/BSTDataBuffer.h
	include/RE/B/BSTEvent.h
	include/RE/B/BSTFreeList.h
	include/RE/B/BSTHashMap.h
	include/RE/B/BSTInterpolator.h
	include/RE/B/BSTMessageQueue.h
	include/RE/B/BSTObjectArena.h
	include/RE/B/BSTOptional.h
	include/RE/B/BSTPoint.h
	include/RE/B/BSTPointerAndFlags.h
	include/RE/B/BSTSingleton.h
	include/RE/B/BSTSmallIndexScatterTable.h
	include/RE/B/BSTSmartPointer.h
	include/RE/B/BSTTuple.h
	include/RE/B/BSTempEffect.h
	include/RE/B/BSTempEffectDebris.h
	include/RE/B/BSTempEffectGeometryDecal.h
	include/RE/B/BSTempEffectParticle.h
	include/RE/B/BSTempEffectSPG.h
	include/RE/B/BSTempEffectScreenSpaceDecal.h
	include/RE/B/BSTempEffectUtil.h
	include/RE/B/BSTempEffectWeaponBlood.h
	include/RE/B/BSTerrainEffect.h
	include/RE/B/BSTextureDB.h
	include/RE/B/BSTextureSet.h
	include/RE/B/BSTextureStreamer.h
	include/RE/B/BSThread.h
	include/RE/B/BSThreadEvent.h
	include/RE/B/BSTimer.h
	include/RE/B/BSTransformDeltaEvent.h
	include/RE/B/BSTranslator.h
	include/RE/B/BSTriShape.h
	include/RE/B/BSUIMessageData.h
	include/RE/B/BSUIScaleformData.h
	include/RE/B/BSUtilities.h
	include/RE/B/BSUtilityShader.h
	include/RE/B/BSVisit.h
	include/RE/B/BS_BUTTON_CODE.h
	include/RE/B/BarrierProjectile.h
	include/RE/B/BarterMenu.h
	include/RE/B/BarterMenuTentativeInventoryUIInterface.h
	include/RE/B/BaseBotConfirmCallback.h
	include/RE/B/BaseExtraList.h
	include/RE/B/BaseFormComponent.h
	include/RE/B/BaseLoadedInventoryModel.h
	include/RE/B/BeamProjectile.h
	include/RE/B/BipedAnim.h
	include/RE/B/Bleedout.h
	include/RE/B/BobbleheadCollected.h
	include/RE/B/BooksRead.h
	include/RE/B/ButtonEvent.h
	include/RE/B/ButtonHintBar.h
	include/RE/B/bhkCollisionQueryResultHandle.h
	include/RE/C/CALCED_OBJECT.h
	include/RE/C/CELLJobs.h
	include/RE/C/CFilter.h
	include/RE/C/CHANGE_TYPES.h
	include/RE/C/CLASS_DATA.h
	include/RE/C/COMMAND_TYPE.h
	include/RE/C/COMPILER_NAME.h
	include/RE/C/CONDITIONITEMOBJECT.h
	include/RE/C/CONDITION_ITEM_DATA.h
	include/RE/C/CONT_DATA.h
	include/RE/C/CachedValueData.h
	include/RE/C/CachedValues.h
	include/RE/C/Calendar.h
	include/RE/C/CameraStates.h
	include/RE/C/CanDisplayNextHUDMessage.h
	include/RE/C/CellAttachDetachEvent.h
	include/RE/C/CellAttachDetachEventSource.h
	include/RE/C/CharacterEvent.h
	include/RE/C/ColorUpdateEvent.h
	include/RE/C/CombatFormulas.h
	include/RE/C/CombatStyleCloseRangeData.h
	include/RE/C/CombatStyleCoverData.h
	include/RE/C/CombatStyleFlightData.h
	include/RE/C/CombatStyleGeneralData.h
	include/RE/C/CombatStyleLongRangeData.h
	include/RE/C/CombatStyleMeleeData.h
	include/RE/C/CombatStyleRangedData.h
	include/RE/C/CombatUtilities.h
	include/RE/C/CommandedActorData.h
	include/RE/C/ComparisonQualifiers.h
	include/RE/C/ConcreteFormFactory.h
	include/RE/C/ConcreteObjectFormFactory.h
	include/RE/C/ConditionCheckParams.h
	include/RE/C/ConeProjectile.h
	include/RE/C/Console.h
	include/RE/C/ConsoleLog.h
	include/RE/C/ContainerItemExtra.h
	include/RE/C/ContainerMenu.h
	include/RE/C/ContainerMenuBase.h
	include/RE/C/ContainerObject.h
	include/RE/C/ControlMap.h
	include/RE/C/CreatureSounds.h
	include/RE/C/CrimeGoldStruct.h
	include/RE/C/CurrentRadiationSourceCount.h
	include/RE/C/CurrentRadsDisplayMagnitude.h
	include/RE/C/CurrentRadsPercentOfLethal.h
	include/RE/C/CursorMenu.h
	include/RE/C/CursorMoveEvent.h
	include/RE/C/CustomMarkerUpdate.h
	include/RE/D/DECAL_DATA_DATA.h
	include/RE/D/DEFAULT_OBJECT.h
	include/RE/D/DEFAULT_OBJECT_DATA.h
	include/RE/D/DEFAULT_OBJECT_TYPE.h
	include/RE/D/DIALOGUE_DATA.h
	include/RE/D/DIALOGUE_SUBTYPE.h
	include/RE/D/DIALOGUE_TYPE.h
	include/RE/D/DIRECTION_VAL.h
	include/RE/D/DamageImpactData.h
	include/RE/D/DecalData.h
	include/RE/D/DefaultObjectFormFactory.h
	include/RE/D/DestructibleObjectData.h
	include/RE/D/DestructibleObjectStage.h
	include/RE/D/DeviceConnectEvent.h
	include/RE/D/DialogueMenu.h
	include/RE/D/DialoguePackage.h
	include/RE/D/DifficultyLevel.h
	include/RE/D/DisableHeavyItemsFunc.h
	include/RE/D/DisconnectHandler.h
	include/RE/D/DisplayItemModel.h
	include/RE/D/DoBeforeNewOrLoadCompletedEvent.h
	include/RE/D/DoorTeleportData.h
	include/RE/E/EDGE_EXTRA_INFO_TYPE.h
	include/RE/E/ENCOUNTER_ZONE_DATA.h
	include/RE/E/ENCOUNTER_ZONE_GAME_DATA.h
	include/RE/E/ENUM_COMPARISON_CONDITION.h
	include/RE/E/ENUM_FORM_ID.h
	include/RE/E/ENUM_LOD_MULT.h
	include/RE/E/EQUIP_TYPE.h
	include/RE/E/EXTRA_DATA_TYPE.h
	include/RE/E/EaseOutInterpolator.h
	include/RE/E/EffectArchetypes.h
	include/RE/E/EffectItem.h
	include/RE/E/EffectItemData.h
	include/RE/E/EffectSetting.h
	include/RE/E/EffectShaderData.h
	include/RE/E/EnchantmentItem.h
	include/RE/E/EquipSlotData.h
	include/RE/E/EquippedItem.h
	include/RE/E/EquippedItemData.h
	include/RE/E/EquippedWeaponData.h
	include/RE/E/ExamineConfirmMenu.h
	include/RE/E/ExamineMenu.h
	include/RE/E/Explosion.h
	include/RE/E/ExteriorCellSingleton.h
	include/RE/E/ExtraAliasInstanceArray.h
	include/RE/E/ExtraBendableSplineParams.h
	include/RE/E/ExtraCellWaterType.h
	include/RE/E/ExtraCharge.h
	include/RE/E/ExtraDataList.h
	include/RE/E/ExtraFavorite.h
	include/RE/E/ExtraHealth.h
	include/RE/E/ExtraInstanceData.h
	include/RE/E/ExtraLeveledCreature.h
	include/RE/E/ExtraLocation.h
	include/RE/E/ExtraLock.h
	include/RE/E/ExtraMapMarker.h
	include/RE/E/ExtraMaterialSwap.h
	include/RE/E/ExtraPowerLinks.h
	include/RE/E/ExtraReferenceHandles.h
	include/RE/E/ExtraStartingWorldOrCell.h
	include/RE/E/ExtraTeleport.h
	include/RE/E/ExtraTextDisplayData.h
	include/RE/E/ExtraUniqueID.h
	include/RE/F/FACTION_CRIME_DATA.h
	include/RE/F/FACTION_CRIME_DATA_VALUES.h
	include/RE/F/FACTION_DATA.h
	include/RE/F/FACTION_RANK.h
	include/RE/F/FACTION_VENDOR_DATA.h
	include/RE/F/FACTION_VENDOR_DATA_VALUES.h
	include/RE/F/FIGHT_REACTION.h
	include/RE/F/FILE_HEADER.h
	include/RE/F/FORM.h
	include/RE/F/FORM_ENUM_STRING.h
	include/RE/F/FUNCTION_DATA.h
	include/RE/F/FatmanDeaths.h
	include/RE/F/FavoriteMgr_Events.h
	include/RE/F/FavoritesManager.h
	include/RE/F/FlameProjectile.h
	include/RE/F/FlatScreenModel.h
	include/RE/F/FleePackage.h
	include/RE/F/FreeCameraState.h
	include/RE/F/FriendshipFactionsStruct.h
	include/RE/Fallout.h
	include/RE/G/GROUP_REACTION.h
	include/RE/G/GUN_STATE.h
	include/RE/G/GameMenuBase.h
	include/RE/G/GamePlayFormulas.h
	include/RE/G/GameScript.h
	include/RE/G/GameUIModel.h
	include/RE/G/GetCurrentPositionFunctor.h
	include/RE/G/GrenadeProjectile.h
	include/RE/G/GridArray.h
	include/RE/G/GridCell.h
	include/RE/G/GridCellArray.h
	include/RE/H/HUDColorTypes.h
	include/RE/H/HUDMenu.h
	include/RE/H/HUDMenuUtils.h
	include/RE/H/HUDModeEvent.h
	include/RE/H/HUDModeType.h
	include/RE/H/HUDModes.h
	include/RE/H/HUDPerkVaultBoyData.h
	include/RE/H/HUDPerkVaultBoySwfDisplayEvent.h
	include/RE/H/Hazard.h
	include/RE/H/HeldStateHandler.h
	include/RE/H/HitData.h
	include/RE/H/HolotapeMenu.h
	include/RE/H/HolotapeStateChanged.h
	include/RE/H/HourPassed.h
	include/RE/I/IAnimationGraphManagerHolder.h
	include/RE/I/IDEvent.h
	include/RE/I/IDLE_DATA.h
	include/RE/I/IEventCallback.h
	include/RE/I/IFormFactory.h
	include/RE/I/IKeywordFormBase.h
	include/RE/I/IMemoryHeap.h
	include/RE/I/IMemoryStore.h
	include/RE/I/IMemoryStoreBase.h
	include/RE/I/IMenu.h
	include/RE/I/IMessageBoxCallback.h
	include/RE/I/IMovementInterface.h
	include/RE/I/IMovementPlayerControls.h
	include/RE/I/IMovementPlayerControlsFilter.h
	include/RE/I/IMovementState.h
	include/RE/I/INPUT_DEVICE.h
	include/RE/I/INPUT_DEVICE_LIGHT_STATE.h
	include/RE/I/INPUT_EVENT_TYPE.h
	include/RE/I/INSTANCE_FILTER.h
	include/RE/I/INTERACTING_STATE.h
	include/RE/I/INTERIOR_DATA.h
	include/RE/I/IPipboyThrottledValue.h
	include/RE/I/IPostAnimationChannelUpdateFunctor.h
	include/RE/I/ITEM_REMOVE_REASON.h
	include/RE/I/IUIMessageData.h
	include/RE/I/ImageSpaceBaseData.h
	include/RE/I/ImageSpaceData.h
	include/RE/I/ImageSpaceEffect.h
	include/RE/I/ImageSpaceEffectBokehDepthOfField.h
	include/RE/I/ImageSpaceEffectDepthOfField.h
	include/RE/I/ImageSpaceEffectFullScreenBlur.h
	include/RE/I/ImageSpaceEffectGetHit.h
	include/RE/I/ImageSpaceEffectHDR.h
	include/RE/I/ImageSpaceEffectMotionBlur.h
	include/RE/I/ImageSpaceEffectOption.h
	include/RE/I/ImageSpaceEffectPipboyScreen.h
	include/RE/I/ImageSpaceEffectRadialBlur.h
	include/RE/I/ImageSpaceEffectTemporalAA.h
	include/RE/I/ImageSpaceLUTData.h
	include/RE/I/ImageSpaceManager.h
	include/RE/I/ImageSpaceModData.h
	include/RE/I/ImageSpaceModifierFinder.h
	include/RE/I/ImageSpaceModifierInstance.h
	include/RE/I/ImageSpaceModifierInstanceDOF.h
	include/RE/I/ImageSpaceModifierInstanceForm.h
	include/RE/I/ImageSpaceModifierInstanceRB.h
	include/RE/I/ImageSpaceModifierInstanceTemp.h
	include/RE/I/ImageSpaceTexture.h
	include/RE/I/ImpactResult.h
	include/RE/I/IngredientItem.h
	include/RE/I/InputEvent.h
	include/RE/I/Interface3D.h
	include/RE/I/Inventory3DManager.h
	include/RE/I/InventoryInterface.h
	include/RE/I/InventoryItemDisplayData.h
	include/RE/I/InventoryUserUIInterface.h
	include/RE/I/InventoryUserUIInterfaceEntry.h
	include/RE/I/InventoryUserUIUtils.h
	include/RE/I/IsPipboyActiveEvent.h
	include/RE/I/ItemCrafted.h
	include/RE/IDs.h
	include/RE/J/JumpHandler.h
	include/RE/K/KeywordType.h
	include/RE/K/KinectEvent.h
	include/RE/L/LEVELED_OBJECT.h
	include/RE/L/LOADED_CELL_DATA.h
	include/RE/L/LOADED_REF_DATA.h
	include/RE/L/LOCK_LEVEL.h
	include/RE/L/LevelIncrease.h
	include/RE/L/LoadingMenu.h
	include/RE/L/LoadingStatusChanged.h
	include/RE/L/LocalMapCameraUpdate.h
	include/RE/L/LocationMarkerArrayUpdate.h
	include/RE/L/LockpickingMenu.h
	include/RE/L/LocksPicked.h
	include/RE/L/LookHandler.h
	include/RE/M/MELEE_ATTACK_SPEED.h
	include/RE/M/MENU_RENDER_CONTEXT.h
	include/RE/M/MESSAGEBOX_BUTTON.h
	include/RE/M/MOVABLE_STATIC_DATA.h
	include/RE/M/MagicItem.h
	include/RE/M/MagicTarget.h
	include/RE/M/Main.h
	include/RE/M/MapMarkerData.h
	include/RE/M/MeleeThrowHandler.h
	include/RE/M/MemoryManager.h
	include/RE/M/MenuControls.h
	include/RE/M/MenuCursor.h
	include/RE/M/MenuModeChangeEvent.h
	include/RE/M/MenuModeCounterChangedEvent.h
	include/RE/M/MenuOpenCloseEvent.h
	include/RE/M/MenuOpenHandler.h
	include/RE/M/MenuTopicManager.h
	include/RE/M/MessageBoxData.h
	include/RE/M/MessageBoxMenu.h
	include/RE/M/MessageMenuManager.h
	include/RE/M/MiddleHighProcessData.h
	include/RE/M/MiddleLowProcessData.h
	include/RE/M/MissileProjectile.h
	include/RE/M/ModConfirmCallback.h
	include/RE/M/ModelReferenceEffect.h
	include/RE/M/Modifiers.h
	include/RE/M/MouseMoveEvent.h
	include/RE/M/Movement.h
	include/RE/M/MovementData.h
	include/RE/N/NEW_REFR_DATA.h
	include/RE/N/NPC_DATA.h
	include/RE/N/NavMesh.h
	include/RE/N/NavMeshInfoMap.h
	include/RE/N/NiAVObject.h
	include/RE/N/NiAlphaProperty.h
	include/RE/N/NiBinaryStream.h
	include/RE/N/NiBound.h
	include/RE/N/NiCamera.h
	include/RE/N/NiCloningProcess.h
	include/RE/N/NiCollisionObject.h
	include/RE/N/NiColor.h
	include/RE/N/NiControllerManager.h
	include/RE/N/NiControllerSequence.h
	include/RE/N/NiExtraData.h
	include/RE/N/NiExtraDataContainer.h
	include/RE/N/NiFile.h
	include/RE/N/NiFrustum.h
	include/RE/N/NiMatrix3.h
	include/RE/N/NiMemManager.h
	include/RE/N/NiMemStream.h
	include/RE/N/NiNPShortPoint3.h
	include/RE/N/NiNode.h
	include/RE/N/NiObject.h
	include/RE/N/NiObjectNET.h
	include/RE/N/NiPoint.h
	include/RE/N/NiPointer.h
	include/RE/N/NiProperty.h
	include/RE/N/NiQuaternion.h
	include/RE/N/NiRTTI.h
	include/RE/N/NiRect.h
	include/RE/N/NiRefObject.h
	include/RE/N/NiShadeProperty.h
	include/RE/N/NiStream.h
	include/RE/N/NiStringExtraData.h
	include/RE/N/NiTArray.h
	include/RE/N/NiTDefaultAllocator.h
	include/RE/N/NiTFlags.h
	include/RE/N/NiTLargeArray.h
	include/RE/N/NiTList.h
	include/RE/N/NiTMap.h
	include/RE/N/NiTPointerAllocator.h
	include/RE/N/NiTPointerMap.h
	include/RE/N/NiTexture.h
	include/RE/N/NiTimeController.h
	include/RE/N/NiTransform.h
	include/RE/N/NiUpdateData.h
	include/RE/N/nsStatsMenuUtils.h
	include/RE/NiRTTI_IDs.h
	include/RE/O/OBJ_ARMA.h
	include/RE/O/OBJ_BOOK.h
	include/RE/O/OBJ_LAND.h
	include/RE/O/OBJ_LIGH.h
	include/RE/O/OBJ_REFR.h
	include/RE/O/OBJ_TREE.h
	include/RE/O/OtherInputEvents.h
	include/RE/P/PACKAGE_DATA.h
	include/RE/P/PACKAGE_OBJECT_TYPE.h
	include/RE/P/PACK_SCHED_DATA.h
	include/RE/P/PART_DATA.h
	include/RE/P/PATH_DATA.h
	include/RE/P/PC_GAMEPAD_TYPE.h
	include/RE/P/PIPBOY_PAGES.h
	include/RE/P/PLAYER_ACTION.h
	include/RE/P/PLAYER_TARGET_LOC.h
	include/RE/P/POWER_ARMOR_HUD_VISIBILITY_RULE.h
	include/RE/P/PTYPE.h
	include/RE/P/PackageEventAction.h
	include/RE/P/PackageList.h
	include/RE/P/PackageSchedule.h
	include/RE/P/PauseMenu.h
	include/RE/P/PerkAdded.h
	include/RE/P/PerkData.h
	include/RE/P/PerkPointIncreaseEvent.h
	include/RE/P/PerkRankData.h
	include/RE/P/PerkUtilities.h
	include/RE/P/PerkValueEvents.h
	include/RE/P/PersistentPassList.h
	include/RE/P/PipboyArray.h
	include/RE/P/PipboyDataGroup.h
	include/RE/P/PipboyDataManager.h
	include/RE/P/PipboyHolotapeMenu.h
	include/RE/P/PipboyInventoryData.h
	include/RE/P/PipboyInventoryMenu.h
	include/RE/P/PipboyInventoryUtils.h
	include/RE/P/PipboyLightEvent.h
	include/RE/P/PipboyLogData.h
	include/RE/P/PipboyLogMenu.h
	include/RE/P/PipboyManager.h
	include/RE/P/PipboyMapData.h
	include/RE/P/PipboyMapMenu.h
	include/RE/P/PipboyMenu.h
	include/RE/P/PipboyObject.h
	include/RE/P/PipboyPerksData.h
	include/RE/P/PipboyPerksMenu.h
	include/RE/P/PipboyPlayerInfoData.h
	include/RE/P/PipboyPlayerInfoMenu.h
	include/RE/P/PipboyPrimitiveValue.h
	include/RE/P/PipboyQuestData.h
	include/RE/P/PipboyQuestMenu.h
	include/RE/P/PipboyRadioController.h
	include/RE/P/PipboyRadioData.h
	include/RE/P/PipboyRadioMenu.h
	include/RE/P/PipboySpecialData.h
	include/RE/P/PipboySpecialMenu.h
	include/RE/P/PipboyStatsData.h
	include/RE/P/PipboyStatsMenu.h
	include/RE/P/PipboyStatusData.h
	include/RE/P/PipboySubMenu.h
	include/RE/P/PipboyThrottleManager.h
	include/RE/P/PipboyValue.h
	include/RE/P/PipboyWorkshopData.h
	include/RE/P/PipboyWorkshopMenu.h
	include/RE/P/PlayerActiveEffectChanged.h
	include/RE/P/PlayerAddicted.h
	include/RE/P/PlayerAmmoCountEvent.h
	include/RE/P/PlayerAmmoCounts.h
	include/RE/P/PlayerAutoAimActorEvent.h
	include/RE/P/PlayerCamera.h
	include/RE/P/PlayerCharacter.h
	include/RE/P/PlayerCharacterQuestEvent.h
	include/RE/P/PlayerCommandTypeEvent.h
	include/RE/P/PlayerControls.h
	include/RE/P/PlayerControlsData.h
	include/RE/P/PlayerControlsMovementData.h
	include/RE/P/PlayerCoverData.h
	include/RE/P/PlayerDifficultySettingChanged.h
	include/RE/P/PlayerInDialogueChanged.h
	include/RE/P/PlayerInputHandler.h
	include/RE/P/PlayerLifeStateChanged.h
	include/RE/P/PlayerUpdateEvent.h
	include/RE/P/PlayerWeaponReloadEvent.h
	include/RE/P/PositionPlayerEvent.h
	include/RE/P/PowerArmor.h
	include/RE/P/PowerArmorGeometry.h
	include/RE/P/PowerArmorLightData.h
	include/RE/P/PowerArmorModMenu.h
	include/RE/P/PowerUtils.h
	include/RE/P/PrecomputedNavmeshInfoPathMap.h
	include/RE/P/ProcessLists.h
	include/RE/P/Projectile.h
	include/RE/P/ProjectileLaunchData.h
	include/RE/Q/QUEST_DATA.h
	include/RE/Q/QUEST_OBJECTIVE_STATE.h
	include/RE/Q/QuickContainerMode.h
	include/RE/Q/QuickContainerStateData.h
	include/RE/Q/QuickContainerStateEvent.h
	include/RE/R/RACE_DATA.h
	include/RE/R/RACE_SIZE.h
	include/RE/R/RANK_DATA.h
	include/RE/R/REFR_LOCK.h
	include/RE/R/RESET_3D_FLAGS.h
	include/RE/R/ReadyWeaponHandler.h
	include/RE/R/RefAttachTechniqueInput.h
	include/RE/R/ReferenceEffect.h
	include/RE/R/ReferenceEffectController.h
	include/RE/R/RepairFailureCallback.h
	include/RE/R/RepeaterData.h
	include/RE/R/ResponseListWrapper.h
	include/RE/R/Rumble.h
	include/RE/RTTI.h
	include/RE/RTTI_IDs.h
	include/RE/S/SCRIPT_EFFECT_DATA.h
	include/RE/S/SCRIPT_FUNCTION.h
	include/RE/S/SCRIPT_HEADER.h
	include/RE/S/SCRIPT_LINE.h
	include/RE/S/SCRIPT_LOCAL.h
	include/RE/S/SCRIPT_OUTPUT.h
	include/RE/S/SCRIPT_PARAMETER.h
	include/RE/S/SCRIPT_PARAM_TYPE.h
	include/RE/S/SCRIPT_REFERENCED_OBJECT.h
	include/RE/S/SEX.h
	include/RE/S/SFRendererInitializedEvent.h
	include/RE/S/SIT_SLEEP_STATE.h
	include/RE/S/SOUND_LEVEL.h
	include/RE/S/SPECIALMenuEvent.h
	include/RE/S/SWFToCodeFunctionHandler.h
	include/RE/S/SayOnceTimeStampStruct.h
	include/RE/S/ScrapHeap.h
	include/RE/S/ScrapItemCallback.h
	include/RE/S/ScreenshotHandler.h
	include/RE/S/Script.h
	include/RE/S/ScriptCompileData.h
	include/RE/S/ScriptCompiler.h
	include/RE/S/ScriptLocals.h
	include/RE/S/ScriptVariable.h
	include/RE/S/ScrollItem.h
	include/RE/S/SendHUDMessage.h
	include/RE/S/SetCullMarkersFunctor.h
	include/RE/S/Setting.h
	include/RE/S/ShaderReferenceEffect.h
	include/RE/S/ShowingDialogueSpeechChallengeAnim.h
	include/RE/S/SimpleAnimationGraphManagerHolder.h
	include/RE/S/SitWaitMenu.h
	include/RE/S/Sky.h
	include/RE/S/SkyEffectController.h
	include/RE/S/SneakHandler.h
	include/RE/S/SpecialRefData.h
	include/RE/S/SpectatorPackage.h
	include/RE/S/SpectatorThreatInfo.h
	include/RE/S/SpellItem.h
	include/RE/S/SplineUtils.h
	include/RE/S/StartMenuBase.h
	include/RE/S/StolenItemValueStruct.h
	include/RE/S/SubGraphIdleRootData.h
	include/RE/S/SubgraphHandle.h
	include/RE/S/SubgraphIdentifier.h
	include/RE/S/SummonPlacementEffect.h
	include/RE/T/TBO_InstanceData.h
	include/RE/T/TEMP_EFFECT_TYPE.h
	include/RE/T/TES.h
	include/RE/T/TESAIForm.h
	include/RE/T/TESActivateEvent.h
	include/RE/T/TESActorBase.h
	include/RE/T/TESActorBaseData.h
	include/RE/T/TESAmmo.h
	include/RE/T/TESBipedModelForm.h
	include/RE/T/TESBoundAnimObject.h
	include/RE/T/TESBoundObject.h
	include/RE/T/TESCamera.h
	include/RE/T/TESCameraState.h
	include/RE/T/TESCellAttachDetachEvent.h
	include/RE/T/TESCellFullyLoadedEvent.h
	include/RE/T/TESChildCell.h
	include/RE/T/TESClass.h
	include/RE/T/TESClimate.h
	include/RE/T/TESCombatStyle.h
	include/RE/T/TESCondition.h
	include/RE/T/TESConditionItem.h
	include/RE/T/TESContainer.h
	include/RE/T/TESContainerChangedEvent.h
	include/RE/T/TESDataHandler.h
	include/RE/T/TESDeathEvent.h
	include/RE/T/TESDescription.h
	include/RE/T/TESEffectShader.h
	include/RE/T/TESEnchantableForm.h
	include/RE/T/TESEnterSneakingEvent.h
	include/RE/T/TESEquipEvent.h
	include/RE/T/TESEyes.h
	include/RE/T/TESFaction.h
	include/RE/T/TESFile.h
	include/RE/T/TESFileArray.h
	include/RE/T/TESFileCollection.h
	include/RE/T/TESFileContainer.h
	include/RE/T/TESFlora.h
	include/RE/T/TESForm.h
	include/RE/T/TESFormDeleteEvent.h
	include/RE/T/TESFormUtil.h
	include/RE/T/TESFullName.h
	include/RE/T/TESFurniture.h
	include/RE/T/TESFurnitureEvent.h
	include/RE/T/TESGlobal.h
	include/RE/T/TESGrass.h
	include/RE/T/TESHarvestEvent.h
	include/RE/T/TESHealthForm.h
	include/RE/T/TESHitEvent.h
	include/RE/T/TESIcon.h
	include/RE/T/TESIdleForm.h
	include/RE/T/TESImageSpace.h
	include/RE/T/TESImageSpaceModifiableForm.h
	include/RE/T/TESImageSpaceModifier.h
	include/RE/T/TESInitScriptEvent.h
	include/RE/T/TESKey.h
	include/RE/T/TESLandTexture.h
	include/RE/T/TESLevCharacter.h
	include/RE/T/TESLevItem.h
	include/RE/T/TESLevSpell.h
	include/RE/T/TESLeveledList.h
	include/RE/T/TESLoadGameEvent.h
	include/RE/T/TESLoadScreen.h
	include/RE/T/TESLocationClearedEvent.h
	include/RE/T/TESMagicCasterForm.h
	include/RE/T/TESMagicEffectApplyEvent.h
	include/RE/T/TESMagicTargetForm.h
	include/RE/T/TESModel.h
	include/RE/T/TESModelRDT.h
	include/RE/T/TESModelTri.h
	include/RE/T/TESNPC.h
	include/RE/T/TESObject.h
	include/RE/T/TESObjectACTI.h
	include/RE/T/TESObjectANIO.h
	include/RE/T/TESObjectARMA.h
	include/RE/T/TESObjectARMO.h
	include/RE/T/TESObjectBOOK.h
	include/RE/T/TESObjectCELL.h
	include/RE/T/TESObjectCONT.h
	include/RE/T/TESObjectDOOR.h
	include/RE/T/TESObjectLAND.h
	include/RE/T/TESObjectLIGH.h
	include/RE/T/TESObjectLoadedEvent.h
	include/RE/T/TESObjectMISC.h
	include/RE/T/TESObjectREFR.h
	include/RE/T/TESObjectSTAT.h
	include/RE/T/TESObjectSTATData.h
	include/RE/T/TESObjectTREE.h
	include/RE/T/TESObjectWEAP.h
	include/RE/T/TESPackage.h
	include/RE/T/TESProduceForm.h
	include/RE/T/TESQuest.h
	include/RE/T/TESQuestEvent.h
	include/RE/T/TESRace.h
	include/RE/T/TESRaceForm.h
	include/RE/T/TESReactionForm.h
	include/RE/T/TESRegion.h
	include/RE/T/TESRegionList.h
	include/RE/T/TESResponse.h
	include/RE/T/TESShout.h
	include/RE/T/TESSoulGem.h
	include/RE/T/TESSound.h
	include/RE/T/TESSpellList.h
	include/RE/T/TESSwitchRaceCompleteEvent.h
	include/RE/T/TESTexture.h
	include/RE/T/TESTexture1024.h
	include/RE/T/TESTopic.h
	include/RE/T/TESTopicInfo.h
	include/RE/T/TESTrackedStatsEvent.h
	include/RE/T/TESValueForm.h
	include/RE/T/TESWaterForm.h
	include/RE/T/TESWeather.h
	include/RE/T/TESWeatherList.h
	include/RE/T/TESWeightForm.h
	include/RE/T/TESWordOfPower.h
	include/RE/T/TESWorldSpace.h
	include/RE/T/TEXTURE_HAVOK_DATA.h
	include/RE/T/TLS.h
	include/RE/T/TOPIC_INFO_DATA.h
	include/RE/T/TOPIC_INFO_SCENEDATA.h
	include/RE/T/TaskQueueInterface.h
	include/RE/T/TerminalHacked.h
	include/RE/T/TerminalHolotapeMenu.h
	include/RE/T/TerminalMenu.h
	include/RE/T/TerminalMenuButtons.h
	include/RE/T/ThirdPersonState.h
	include/RE/T/ThumbstickEvent.h
	include/RE/T/TravelMarkerStateChange.h
	include/RE/T/TrespassPackage.h
	include/RE/T/TutorialEvent.h
	include/RE/U/UI.h
	include/RE/U/UIAdvanceMenusFunctionCompleteEvent.h
	include/RE/U/UIMenuEntry.h
	include/RE/U/UIMessage.h
	include/RE/U/UIMessageQueue.h
	include/RE/U/UIShaderColors.h
	include/RE/U/UIShaderFXInfo.h
	include/RE/U/UIUtils.h
	include/RE/U/UI_DEPTH_PRIORITY.h
	include/RE/U/UI_MENU_FLAGS.h
	include/RE/U/UI_MESSAGE_RESULTS.h
	include/RE/U/UI_MESSAGE_TYPE.h
	include/RE/U/UniqueNPCData.h
	include/RE/U/UnloadedRefData.h
	include/RE/U/UserEventEnabledEvent.h
	include/RE/U/UserEvents.h
	include/RE/U/UsesBSGFXFunctionHandler.h
	include/RE/V/VATS.h
	include/RE/V/VATSEvents.h
	include/RE/V/VOICE_TYPE_DATA.h
	include/RE/VTABLE_IDs.h
	include/RE/W/WARNING_TYPES.h
	include/RE/W/WEAPONHITBEHAVIOR.h
	include/RE/W/WEAPON_CULL_TYPE.h
	include/RE/W/WEAPON_FLAGS.h
	include/RE/W/WEAPON_RUMBLE_PATTERN.h
	include/RE/W/WEAPON_STATE.h
	include/RE/W/WEAPON_TYPE.h
	include/RE/W/WORLD_MAP_DATA.h
	include/RE/W/WORLD_MAP_OFFSET_DATA.h
	include/RE/W/WaterShaderData.h
	include/RE/W/WeaponAnimationGraphManagerHolder.h
	include/RE/W/WeatherEntry.h
	include/RE/W/WorkbenchData.h
	include/RE/W/WorkbenchMenuBase.h
	include/RE/W/Workshop.h
	include/RE/W/WorkshopMenu.h
	include/RE/X/XPChangeData.h
	include/REL/ASM.h
	include/REL/Hook.h
	include/REL/HookObject.h
	include/REL/HookStore.h
	include/REL/IAT.h
	include/REL/ID.h
	include/REL/IDDB.h
	include/REL/Module.h
	include/REL/Offset.h
	include/REL/Offset2ID.h
	include/REL/REL.h
	include/REL/Relocation.h
	include/REL/Segment.h
	include/REL/Trampoline.h
	include/REL/Utility.h
	include/REL/Version.h
	include/REX/PS4.h
	include/REX/PS4/SCEPAD.h
	include/REX/REX.h
	include/REX/REX/Enum.h
	include/REX/REX/EnumSet.h
	include/REX/REX/INI.h
	include/REX/REX/JSON.h
	include/REX/REX/LOG.h
	include/REX/REX/Setting.h
	include/REX/REX/Singleton.h
	include/REX/REX/TOML.h
	include/REX/W32.h
	include/REX/W32/ADVAPI32.h
	include/REX/W32/BASE.h
	include/REX/W32/BCRYPT.h
	include/REX/W32/COM.h
	include/REX/W32/COMPTR.h
	include/REX/W32/D3D.h
	include/REX/W32/D3D11.h
	include/REX/W32/D3D11_1.h
	include/REX/W32/D3D11_2.h
	include/REX/W32/D3D11_3.h
	include/REX/W32/D3D11_4.h
	include/REX/W32/D3DCOMPILER.h
	include/REX/W32/DBGHELP.h
	include/REX/W32/DINPUT.h
	include/REX/W32/DXGI.h
	include/REX/W32/DXGI_2.h
	include/REX/W32/DXGI_3.h
	include/REX/W32/DXGI_4.h
	include/REX/W32/DXGI_5.h
	include/REX/W32/DXGI_6.h
	include/REX/W32/KERNEL32.h
	include/REX/W32/NT.h
	include/REX/W32/OLE32.h
	include/REX/W32/SHELL32.h
	include/REX/W32/USER32.h
	include/REX/W32/VERSION.h
	include/REX/W32/XINPUT.h
	include/Scaleform/A/AcquireInterface.h
	include/Scaleform/A/AllocInfo.h
	include/Scaleform/A/Allocator.h
	include/Scaleform/A/Array.h
	include/Scaleform/A/ArrayPaged.h
	include/Scaleform/A/Atomic.h
	include/Scaleform/A/AutoPtr.h
	include/Scaleform/E/Event.h
	include/Scaleform/F/Flags.h
	include/Scaleform/G/GFx_AS3_ASVM.h
	include/Scaleform/G/GFx_AS3_Abc_ClassTable.h
	include/Scaleform/G/GFx_AS3_Abc_ConstPool.h
	include/Scaleform/G/GFx_AS3_Abc_File.h
	include/Scaleform/G/GFx_AS3_Abc_MbiInd.h
	include/Scaleform/G/GFx_AS3_Abc_MetadataTable.h
	include/Scaleform/G/GFx_AS3_Abc_MethodBodyTable.h
	include/Scaleform/G/GFx_AS3_Abc_MethodTable.h
	include/Scaleform/G/GFx_AS3_Abc_NamespaceInfo.h
	include/Scaleform/G/GFx_AS3_Abc_NamespaceKind.h
	include/Scaleform/G/GFx_AS3_Abc_ScriptTable.h
	include/Scaleform/G/GFx_AS3_Abc_TraitTable.h
	include/Scaleform/G/GFx_AS3_CallFrame.h
	include/Scaleform/G/GFx_AS3_FlashUI.h
	include/Scaleform/G/GFx_AS3_GASRefCountBase.h
	include/Scaleform/G/GFx_AS3_MovieRoot.h
	include/Scaleform/G/GFx_AS3_RefCountBaseGC.h
	include/Scaleform/G/GFx_AS3_SPtr.h
	include/Scaleform/G/GFx_AS3_StringManager.h
	include/Scaleform/G/GFx_AS3_TypeInfo.h
	include/Scaleform/G/GFx_AS3_VM.h
	include/Scaleform/G/GFx_AS3_VMAbcFile.h
	include/Scaleform/G/GFx_AS3_VMFile.h
	include/Scaleform/G/GFx_AS3_Value.h
	include/Scaleform/G/GFx_ASConstString.h
	include/Scaleform/G/GFx_ASIntervalTimerIntf.h
	include/Scaleform/G/GFx_ASMovieRootBase.h
	include/Scaleform/G/GFx_ASString.h
	include/Scaleform/G/GFx_ASStringBuiltinManagerT.h
	include/Scaleform/G/GFx_ASStringManager.h
	include/Scaleform/G/GFx_ASStringNode.h
	include/Scaleform/G/GFx_ASStringNodeHolder.h
	include/Scaleform/G/GFx_ActionControl.h
	include/Scaleform/G/GFx_ExporterInfo.h
	include/Scaleform/G/GFx_ExternalInterface.h
	include/Scaleform/G/GFx_ExternalLibPtr.h
	include/Scaleform/G/GFx_FSCommandHandler.h
	include/Scaleform/G/GFx_FileTypeConstants.h
	include/Scaleform/G/GFx_FocusGroupDescr.h
	include/Scaleform/G/GFx_FocusMovedType.h
	include/Scaleform/G/GFx_FunctionHandler.h
	include/Scaleform/G/GFx_HeapId.h
	include/Scaleform/G/GFx_KeyboardState.h
	include/Scaleform/G/GFx_Loader.h
	include/Scaleform/G/GFx_LogBase.h
	include/Scaleform/G/GFx_LogState.h
	include/Scaleform/G/GFx_MemoryContext.h
	include/Scaleform/G/GFx_MemoryParams.h
	include/Scaleform/G/GFx_Movie.h
	include/Scaleform/G/GFx_MovieDef.h
	include/Scaleform/G/GFx_MovieImpl.h
	include/Scaleform/G/GFx_MultitouchInterface.h
	include/Scaleform/G/GFx_PlayState.h
	include/Scaleform/G/GFx_Resource.h
	include/Scaleform/G/GFx_ResourceId.h
	include/Scaleform/G/GFx_ResourceKey.h
	include/Scaleform/G/GFx_ResourceLibBase.h
	include/Scaleform/G/GFx_StatAmp.h
	include/Scaleform/G/GFx_StatFontCache.h
	include/Scaleform/G/GFx_StatGroup.h
	include/Scaleform/G/GFx_StatIME.h
	include/Scaleform/G/GFx_StatMovieData.h
	include/Scaleform/G/GFx_StatMovieView.h
	include/Scaleform/G/GFx_State.h
	include/Scaleform/G/GFx_StateBag.h
	include/Scaleform/G/GFx_System.h
	include/Scaleform/G/GFx_Translator.h
	include/Scaleform/G/GFx_UserEventHandler.h
	include/Scaleform/G/GFx_Value.h
	include/Scaleform/G/GFx_Viewport.h
	include/Scaleform/L/List.h
	include/Scaleform/L/Lock.h
	include/Scaleform/L/Log.h
	include/Scaleform/L/LogMessageId.h
	include/Scaleform/M/Memory.h
	include/Scaleform/M/MemoryHeap.h
	include/Scaleform/M/Mutex.h
	include/Scaleform/N/NewOverrideBase.h
	include/Scaleform/P/Ptr.h
	include/Scaleform/R/RefCountBase.h
	include/Scaleform/R/Render_Color.h
	include/Scaleform/R/Render_ContextImpl_Context.h
	include/Scaleform/R/Render_ContextImpl_ContextCaptureNotify.h
	include/Scaleform/R/Render_ContextImpl_ContextData_ImplMixin.h
	include/Scaleform/R/Render_ContextImpl_ContextLock.h
	include/Scaleform/R/Render_ContextImpl_DisplayHandle.h
	include/Scaleform/R/Render_ContextImpl_Entry.h
	include/Scaleform/R/Render_ContextImpl_EntryChange.h
	include/Scaleform/R/Render_ContextImpl_EntryData.h
	include/Scaleform/R/Render_ContextImpl_EntryListAccessor.h
	include/Scaleform/R/Render_ContextImpl_EntryPage.h
	include/Scaleform/R/Render_ContextImpl_EntryPageBase.h
	include/Scaleform/R/Render_ContextImpl_EntryTable.h
	include/Scaleform/R/Render_ContextImpl_RTHandle.h
	include/Scaleform/R/Render_ContextImpl_RenderNotify.h
	include/Scaleform/R/Render_ContextImpl_SnapshotPage.h
	include/Scaleform/R/Render_EdgeAAMode.h
	include/Scaleform/R/Render_Interfaces.h
	include/Scaleform/R/Render_LinearHeap.h
	include/Scaleform/R/Render_Matrix.h
	include/Scaleform/R/Render_PagedItemBuffer.h
	include/Scaleform/R/Render_Point.h
	include/Scaleform/R/Render_Rect.h
	include/Scaleform/R/Render_ScreenToWorld.h
	include/Scaleform/R/Render_ThreadCommand.h
	include/Scaleform/R/Render_ThreadCommandQueue.h
	include/Scaleform/R/Render_TreeContainer.h
	include/Scaleform/R/Render_TreeNode.h
	include/Scaleform/R/Render_TreeRoot.h
	include/Scaleform/R/Render_TreeShape.h
	include/Scaleform/R/Render_Viewport.h
	include/Scaleform/S/StatBag.h
	include/Scaleform/S/StatBasicValues.h
	include/Scaleform/S/String.h
	include/Scaleform/S/StringDataPtr.h
	include/Scaleform/S/SysAlloc.h
	include/Scaleform/S/System.h
	include/Scaleform/Scaleform.h
	include/Scaleform/T/ThreadId.h
	include/Scaleform/W/WaitCondition.h
	include/Scaleform/W/Waitable.h
	src/F4SE/API.cpp
	src/F4SE/Impl/PCH.cpp
	src/F4SE/InputMap.cpp
	src/F4SE/Interfaces.cpp
	src/F4SE/Logger.cpp
	src/RE/A/Actor.cpp
	src/RE/B/BGSCreatedObjectManager.cpp
	src/RE/B/BGSInventoryItem.cpp
	src/RE/B/BGSKeyword.cpp
	src/RE/B/BGSKeywordForm.cpp
	src/RE/B/BGSLocation.cpp
	src/RE/B/BGSObjectInstanceExtra.cpp
	src/RE/B/BSCRC32.cpp
	src/RE/B/BSFixedString.cpp
	src/RE/B/BSPointerHandle.cpp
	src/RE/B/BSResource.cpp
	src/RE/B/BSResourceNiBinaryStream.cpp
	src/RE/B/BSResource_Stream.cpp
	src/RE/B/BSResource_StreamBase.cpp
	src/RE/B/BSScaleformManager.cpp
	src/RE/B/BSScript_Array.cpp
	src/RE/B/BSScript_Internal_VirtualMachine.cpp
	src/RE/B/BSScript_Object.cpp
	src/RE/B/BSScript_ObjectTypeInfo.cpp
	src/RE/B/BSScript_PackedInstructionStream.cpp
	src/RE/B/BSScript_StackFrame.cpp
	src/RE/B/BSScript_Struct.cpp
	src/RE/B/BSScript_StructTypeInfo.cpp
	src/RE/B/BSScript_TypeInfo.cpp
	src/RE/B/BSScript_Variable.cpp
	src/RE/B/BSSpinLock.cpp
	src/RE/B/BSSpring_SpringState.cpp
	src/RE/B/BSTArray.cpp
	src/RE/B/BSTAtomicValue.cpp
	src/RE/B/BSTDataBuffer.cpp
	src/RE/B/BSTInterpolator.cpp
	src/RE/B/BSTPoint.cpp
	src/RE/B/BSVisit.cpp
	src/RE/B/ButtonEvent.cpp
	src/RE/C/Calendar.cpp
	src/RE/C/CharacterEvent.cpp
	src/RE/C/CursorMoveEvent.cpp
	src/RE/D/DeviceConnectEvent.cpp
	src/RE/E/ExtraInstanceData.cpp
	src/RE/Fallout.cpp
	src/RE/G/GetCurrentPositionFunctor.cpp
	src/RE/I/IDEvent.cpp
	src/RE/I/InventoryInterface.cpp
	src/RE/K/KinectEvent.cpp
	src/RE/M/MenuCursor.cpp
	src/RE/M/MouseMoveEvent.cpp
	src/RE/N/NiAVObject.cpp
	src/RE/N/NiBinaryStream.cpp
	src/RE/N/NiMatrix3.cpp
	src/RE/N/NiObjectNET.cpp
	src/RE/N/NiPoint.cpp
	src/RE/N/NiRect.cpp
	src/RE/N/NiTransform.cpp
	src/RE/P/PlayerCharacter.cpp
	src/RE/S/Setting.cpp
	src/RE/T/TESFullName.cpp
	src/RE/T/TESNPC.cpp
	src/RE/T/TESObjectCELL.cpp
	src/RE/T/TESValueForm.cpp
	src/RE/T/ThumbstickEvent.cpp
	src/RE/W/WorkbenchMenuBase.cpp
	src/REL/HookObject.cpp
	src/REL/HookStore.cpp
	src/REL/IAT.cpp
	src/REL/IDDB.cpp
	src/REL/Module.cpp
	src/REL/Trampoline.cpp
	src/REL/Utility.cpp
	src/REL/Version.cpp
	src/REX/REX.cpp
	src/REX/W32.cpp
	src/Scaleform/G/GFx_Movie.cpp
	src/Scaleform/Scaleform.cpp
)
